AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nxtpoll-api

  SAM Template for nxtpoll-api

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"
        AllowMethods:
          - "*"

  NxtpollApiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
    Properties:
      CodeUri: ./rust_app/  # Assumes your Cargo.toml is in the root directory
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          ENVIRONMENT: production

Outputs:
  NxtpollApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  NxtpollApiFunction:
    Description: "Nxtpoll API Lambda Function ARN"
    Value: !GetAtt NxtpollApiFunction.Arn
  NxtpollApiFunctionIamRole:
    Description: "Implicit IAM Role created for Nxtpoll API function"
    Value: !GetAtt NxtpollApiFunctionRole.Arn
